name: brianho
favicon: null
layout_spectrum: 0.7781694182194769
typography_spectrum: 0.5739982598461211
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7338322924915701
  lightness: 0.35675583500415087
  saturation: 0.1062818393111229
  rhythmicContrast: 0.10760944942012429
purpose: []
